---
- name: Copy files
  copy:
    src: "{{ source_dir }}/{{ item }}"
    dest: "{{ dest_dir }}/{{ item }}"
  with_items: "{{ files }}"

- name: Copy files
  copy:
    src: files/application.properties
    dest: /opt/application.properties

- name: Make start.sh script executable
  become: true
  file:
      path: /home/ubuntu/start.sh
      mode: '+x'