---
  - name: Check operating system
    debug:
      msg: "The operating system is {{ ansible_facts['os_family'] }}"
    when: ansible_facts['os_family'] == "Debian"
  
  - name: Install Nginx on Server
    apt: 
      name: nginx 
      state: latest
  
  - name: Copy Nginx Index HTML 
    template:
      src: index.html.j2
      dest: /var/www/html/index.html 
  
  - name: Start and enable a service
    service:
      name: nginx
      state: started
      enabled: yes
