---
- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Install Python 3
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install boto3 using apt
  apt:
    name: python3-boto3
    state: present
  become: yes

- name: Install dependencies
  apt:
    name: 
     - curl
     - unzip
    state: present

- name: Download AWS CLI installation script
  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"

- name: Unzip AWS CLI installation package
  unarchive:
     src: /tmp/awscliv2.zip
     dest: /tmp/
     remote_src: yes

- name: Install AWS CLI
  shell: sudo /tmp/aws/install

- name: Install Java JDK 17
  apt:
    name: openjdk-17-jdk
    state: present
